/* =========================================================================
   PHOTO LABEL SHEET  —  generated from the Photo Organizer
   Edit captions live: open any project page with  #edit  at the end of the URL,
   type captions, then "Copy label sheet" and paste the result back over this file.
   Project ids: uh88-weather · rose-arm · mini-bridge · steel-bridge ·
                soma-pump · stair-robot · kealakehe · personal
   ========================================================================= */

window.PHOTOS = [
  { file: "uh88-cover.jpg", project: "uh88-weather", step: "cover", caption: "" },
  { file: "IMG_6886.jpg", project: "uh88-weather", step: "process-1", caption: "", desc: "Studied the existing roof sensors and located possible mounting locations" },
  { file: "IMG_6888.jpg", project: "uh88-weather", step: "process-1.1", caption: "", desc: "Studied the existing roof sensors and located possible mounting locations" },
  { file: "IMG_6943.jpg", project: "uh88-weather", step: "process-2", caption: "", title: "Design" },
  { file: "IMG_7295.jpg", project: "uh88-weather", step: "process-2", caption: "" },
  { file: "IMG_7087.jpg", project: "uh88-weather", step: "process-3", caption: "", desc: "Soldered wires, tested code, built the Unistrut frame, and assembled the rails." },
  { file: "IMG_7088.jpg", project: "uh88-weather", step: "process-3", caption: "", desc: "Soldered wires, tested code, built the Unistrut frame, and assembled the rails." },
  { file: "IMG_7216.jpg", project: "uh88-weather", step: "process-4.2", caption: "" },
  { file: "IMG_7284.jpg", project: "uh88-weather", step: "process-3", caption: "", desc: "Soldered wires, tested code, built the Unistrut frame, and assembled the rails." },
  { file: "IMG_7291.jpg", project: "uh88-weather", step: "process-5", caption: "" },
  { file: "IMG_6940.jpg", project: "uh88-weather", step: "gallery", caption: "" },
  { file: "IMG_6942.jpg", project: "uh88-weather", step: "gallery", caption: "" },
  { file: "IMG_6946.jpg", project: "uh88-weather", step: "gallery", caption: "" },
  { file: "IMG_7286.jpg", project: "uh88-weather", step: "gallery", caption: "" },
  { file: "IMG_7287.jpg", project: "uh88-weather", step: "process-4.1", caption: "" },
  { file: "IMG_7289.jpg", project: "uh88-weather", step: "gallery", caption: "" },
  { file: "IMG_7297.jpg", project: "uh88-weather", step: "gallery", caption: "" },
  { file: "IMG_7475.jpg", project: "uh88-weather", step: "gallery", caption: "" },
  { file: "78174451262__7ACCAE33-43A1-41AF-89D6-921FA8FAA522.jpg", project: "rose-arm", step: "process-1", caption: "", title: "initial designs", desc: "Created a cycloidal gear box based off of online designs, and configurations." },
  { file: "IMG_5303.jpg", project: "rose-arm", step: "process-1", caption: "", desc: "Created a cycloidal gear box based off of online designs, and configurations." },
  { file: "IMG_5320.jpg", project: "rose-arm", step: "process-2", caption: "", title: "Prototyping", desc: "Started manufacturing and testing." },
  { file: "IMG_5645.jpg", project: "rose-arm", step: "process-3", caption: "", title: "Iteration cycle", desc: "Created a concept design, and iterated the cycloidal gearbox until we switched to planetaries." },
  { file: "IMG_7334.jpg", project: "rose-arm", step: "cover", caption: "" },
  { file: "IMG_5646.jpg", project: "rose-arm", step: "gallery", caption: "" },
  { file: "IMG_6553.jpg", project: "rose-arm", step: "process-4", caption: "", desc: "6 DoF arm fully put together with tested planetary gearboxes." },
  { file: "76216844423__2135E1AA-599D-4CDA-8B65-0733BA856E86.jpg", project: "rose-arm", step: "gallery", caption: "" },
  { file: "IMG_2431.jpg", project: "rose-arm", step: "gallery", caption: "" },
  { file: "IMG_2446.jpg", project: "rose-arm", step: "gallery", caption: "" },
  { file: "IMG_2776.jpg", project: "rose-arm", step: "gallery", caption: "" },
  { file: "IMG_3503.jpg", project: "rose-arm", step: "gallery", caption: "" },
  { file: "0A3EA181-2469-4CFB-8F04-9F77999EAFA6.jpg", project: "mini-bridge", step: "gallery", caption: "" },
  { file: "IMG_5481.jpg", project: "mini-bridge", step: "process-2.0", caption: "", title: "Assembly/ Testing", desc: "Assembled the printed parts from the CAD, and load tested them." },
  { file: "IMG_5485.jpg", project: "mini-bridge", step: "gallery", caption: "" },
  { file: "IMG_5487.jpg", project: "mini-bridge", step: "gallery", caption: "" },
  { file: "IMG_5492.jpg", project: "mini-bridge", step: "process-2.1", caption: "", title: "Assembly/ Testing", desc: "Assembled the printed parts from the CAD, and load tested them." },
  { file: "IMG_5599.jpg", project: "mini-bridge", step: "process-2.2", caption: "", title: "Assembly/ Testing", desc: "Assembled the printed parts from the CAD, and load tested them." },
  { file: "IMG_5626.jpg", project: "mini-bridge", step: "process-1.0", caption: "", title: "initial designs", desc: "Used Onshape to CAD up basic ideas of a bridge." },
  { file: "IMG_5695.jpg", project: "mini-bridge", step: "gallery", caption: "" },
  { file: "IMG_5703.jpg", project: "mini-bridge", step: "process-3.0", caption: "", title: "Iteration/ Features", desc: "Added new features to our bridge to set us apart, and have different connections" },
  { file: "IMG_5736.jpg", project: "mini-bridge", step: "process-4.0", caption: "", desc: "Printing, and testing our final prototype." },
  { file: "IMG_5974.jpg", project: "mini-bridge", step: "cover", caption: "" },
  { file: "IMG_8065.jpg", project: "steel-bridge", step: "cover", caption: "" },
  { file: "IMG_1760.jpg", project: "steel-bridge", step: "process-1", caption: "", title: "Design & Training", desc: "Got trained to use the welder to create rigid connections between members" },
  { file: "steel-bridge-team.jpg", project: "steel-bridge", step: "process-3.0", caption: "" },
  { file: "IMG_1477.jpg", project: "steel-bridge", step: "process-4.0", caption: "" },
  { file: "IMG_7143.jpg", project: "steel-bridge", step: "process-5", caption: "" },
  { file: "pumpcover.jpg", project: "soma-pump", step: "cover", caption: "" },
  { file: "IMG_5514.jpg", project: "soma-pump", step: "process-2", caption: "", title: "Iteration", desc: "Redesigned the pump to accommodate more spinners for a smoother flow." },
  { file: "IMG_4242-clip.webm", project: "soma-pump", step: "process-1.0", caption: "", title: "Initial Design", desc: "Prototyped with 3D printing and created a peristaltic pump that can pump out water.", dir: "videos/soma-pump" },
  { file: "IMG_4453-clip.webm", project: "soma-pump", step: "gallery", caption: "", dir: "videos/soma-pump" },
  { file: "IMG_4456-clip.webm", project: "soma-pump", step: "process-3.0", caption: "", title: "Upgrading to elastomer", desc: "Used the new design to test with Ecoflex (silicon) B to see if it can extrude.", dir: "videos/soma-pump" },
  { file: "IMG_4577-clip.webm", project: "soma-pump", step: "gallery", caption: "", dir: "videos/soma-pump" },
  { file: "IMG_5490-clip.webm", project: "soma-pump", step: "process-3.1", caption: "", title: "Extrusion testing", desc: "Used the new design to test with Ecoflex (silicon) B to see if it can extrude.", dir: "videos/soma-pump" },
  { file: "IMG_6323-clip.webm", project: "soma-pump", step: "process-4.0", caption: "", title: "Double Trouble", desc: "Doubled the motors, and tuned the subsystem for clean, repeatable construction.", dir: "videos/soma-pump" },
  { file: "IMG_6367-clip.webm", project: "soma-pump", step: "gallery", caption: "", dir: "videos/soma-pump" },
  { file: "IMG_6369-clip.webm", project: "soma-pump", step: "gallery", caption: "", dir: "videos/soma-pump" },
  { file: "IMG_6422-clip.webm", project: "soma-pump", step: "process-5.0", caption: "", title: "Current setup", desc: "Refining the design and integrating the pump subsystem with a closed feedback loop for PID control.", dir: "videos/soma-pump" },
  { file: "stairmaster-cover.jpg", project: "stair-robot", step: "cover", caption: "" },
  { file: "IMG_4089.jpg", project: "stair-robot", step: "process-1", caption: "", desc: "After the competition was announced, my friend and I went to the stairs to start getting data." },
  { file: "IMG_4200.jpg", project: "stair-robot", step: "process-2", caption: "", title: "Prototyping", desc: "Printed and tested sprockets for the chain we used in our drivetrain." },
  { file: "IMG_4211.jpg", project: "stair-robot", step: "process-2", caption: "", desc: "Printed and tested sprockets for the chain we used in our drivetrain." },
  { file: "IMG_4271.jpg", project: "stair-robot", step: "process-2", caption: "", desc: "Printed and tested sprockets for the chain we used in our drivetrain." },
  { file: "IMG_3612.jpg", project: "stair-robot", step: "process-4", caption: "(This ended up back firing, and we switched back to the old sprockets)", title: "Iterating", desc: "The night before the competition, we sought to replace all the old sprockets with new ones." },
  { file: "IMG_1037.jpg", project: "stair-robot", step: "process-5.0", caption: "" },
  { file: "IMG_2048.jpg", project: "stair-robot", step: "gallery", caption: "" },
  { file: "IMG_4320.jpg", project: "stair-robot", step: "gallery", caption: "" },
  { file: "IMG_9454.jpg", project: "kealakehe", step: "process-1", caption: "" },
  { file: "1CAEA98B-4303-4993-B4BE-D700FBB9C526.jpg", project: "kealakehe", step: "process-2", caption: "" },
  { file: "IMG_9670.jpg", project: "kealakehe", step: "process-3", caption: "" },
  { file: "IMG_9676.jpg", project: "kealakehe", step: "process-4", caption: "" },
  { file: "318f679c-a897-48e1-8fb6-d25ff6b70024.jpg", project: "kealakehe", step: "cover", caption: "" },
  { file: "4A18B60F-AB09-42AF-B88D-B1497229DDDC.jpg", project: "kealakehe", step: "gallery", caption: "" },
  { file: "IMG_7885.jpg", project: "kealakehe", step: "gallery", caption: "" },
  { file: "IMG_9738.jpg", project: "kealakehe", step: "gallery", caption: "" },
  { file: "IMG_9886.jpg", project: "kealakehe", step: "gallery", caption: "" },
  { file: "IMG_0398.jpg", project: "personal", step: "gallery", caption: "" },
  { file: "IMG_5021.jpg", project: "personal", step: "gallery", caption: "" },
  { file: "IMG_6243.jpg", project: "personal", step: "gallery", caption: "" },
  { file: "IMG_6901.jpg", project: "personal", step: "gallery", caption: "" },
  { file: "IMG_7858.jpg", project: "personal", step: "gallery", caption: "" },
  { file: "IMG_4567_Original.jpg", project: "personal", step: "portrait", caption: "" },
  { file: "IMG_7737.jpg", project: "personal", step: "portrait", caption: "" },
  { file: "20260208_011807-clip.webm", project: "rose-arm", step: "process-2.1", caption: "", title: "Prototyping", desc: "Started manufacturing and testing.", dir: "videos/rose-arm" },
  { file: "IMG_1775-clip.webm", project: "rose-arm", step: "gallery", caption: "", dir: "videos/rose-arm" },
  { file: "IMG_2778-clip.webm", project: "rose-arm", step: "gallery", caption: "", dir: "videos/rose-arm" },
  { file: "IMG_2956-clip.webm", project: "rose-arm", step: "gallery", caption: "", dir: "videos/rose-arm" },
  { file: "IMG_5155-clip.webm", project: "rose-arm", step: "process-4.0", caption: "", desc: "6 DoF arm fully put together with tested planetary gearboxes.", dir: "videos/rose-arm" },
  { file: "IMG_5319-clip.webm", project: "rose-arm", step: "gallery", caption: "", dir: "videos/rose-arm" },
  { file: "IMG_5566-clip.webm", project: "rose-arm", step: "process-3.2", caption: "Test 2.0, we came in on storming weather to test.", title: "Iteration cycle", desc: "Created a concept design, and iterated the cycloidal gearbox until we switched to planetaries.", dir: "videos/rose-arm" },
  { file: "IMG_5576-clip.webm", project: "rose-arm", step: "process-3.3", caption: "A few days after that we tried again.", title: "Iteration cycle", desc: "Created a concept design, and iterated the cycloidal gearbox until we switched to planetaries.", dir: "videos/rose-arm" },
  { file: "IMG_5587-clip.webm", project: "rose-arm", step: "process-3.4", caption: "And again.", title: "Iteration cycle", desc: "Created a concept design, and iterated the cycloidal gearbox until we switched to planetaries.", dir: "videos/rose-arm" },
  { file: "IMG_5607-clip.webm", project: "rose-arm", step: "process-3.5", caption: "And another time.", title: "Iteration cycle", desc: "Created a concept design, and iterated the cycloidal gearbox until we switched to planetaries.", dir: "videos/rose-arm" },
  { file: "IMG_5632-clip.webm", project: "rose-arm", step: "process-4.1", caption: "", desc: "6 DoF arm fully put together with tested planetary gearboxes.", dir: "videos/rose-arm" },
  { file: "IMG_5684-clip.webm", project: "rose-arm", step: "process-5.1", caption: "", dir: "videos/rose-arm" },
  { file: "IMG_6178-clip.webm", project: "rose-arm", step: "process-3.0", caption: "", title: "Iteration cycle", desc: "Created a concept design, and iterated the cycloidal gearbox until we switched to planetaries.", dir: "videos/rose-arm" },
  { file: "IMG_6673-clip.webm", project: "rose-arm", step: "process-5.0", caption: "Using the arm to flip switches for the Equipment Servicing Mission", dir: "videos/rose-arm" },
  { file: "IMG_2520-clip.webm", project: "steel-bridge", step: "process-2.0", caption: "", dir: "videos/steel-bridge" },
  { file: "IMG_2493-clip.webm", project: "steel-bridge", step: "process-2.1", caption: "", dir: "videos/steel-bridge" },
  { file: "IMG_2828-clip.webm", project: "steel-bridge", step: "gallery", caption: "", dir: "videos/steel-bridge" },
  { file: "IMG_9669-clip.webm", project: "kealakehe", step: "process-3.0", caption: "", dir: "videos/kealakehe" },
  { file: "IMG_9710-clip.webm", project: "kealakehe", step: "process-5.0", caption: "", dir: "videos/kealakehe" },
  { file: "IMG_9732-clip.webm", project: "kealakehe", step: "process-5.1", caption: "", dir: "videos/kealakehe" },
  { file: "IMG_2050-clip.webm", project: "stair-robot", step: "process-3.0", caption: "", title: "TESTIng", dir: "videos/stair-robot" },
  { file: "IMG_4374-clip.webm", project: "stair-robot", step: "process-3.1", caption: "", dir: "videos/stair-robot" },
  { file: "20260328_132434-clip.webm", project: "mini-bridge", step: "process-5.0", caption: "", title: "Competition", desc: "Competed at PSWS 2026 and got 5th overall.", dir: "videos/mini-bridge" },
  { file: "IMG_5730-clip.webm", project: "mini-bridge", step: "process-4.1", caption: "", desc: "Printing, and testing our final prototype.", dir: "videos/mini-bridge" },
  { file: "IMG_5735-clip.webm", project: "mini-bridge", step: "process-3.1", caption: "Got rid of that connection because it didn't help.", title: "Iteration/ Features", desc: "Added new features to our bridge to set us apart, and have different connections", dir: "videos/mini-bridge" },
  { file: "IMG_5990-clip.webm", project: "mini-bridge", step: "process-4.2", caption: "", desc: "Printing, and testing our final prototype.", dir: "videos/mini-bridge" },
  { file: "IMG_6170-clip.webm", project: "mini-bridge", step: "gallery", caption: "", dir: "videos/mini-bridge" },
  { file: "IMG_6364-clip.webm", project: "mini-bridge", step: "process-5.1", caption: "", desc: "Competed at PSWS 2026 and got 5th overall.", dir: "videos/mini-bridge" },
  { file: "BeReal-DualVideo-Jul-15-2026-clip.webm", project: "uh88-weather", step: "gallery", caption: "", dir: "videos/uh88-weather" },
  { file: "IMG_6890-clip.webm", project: "uh88-weather", step: "gallery", caption: "", dir: "videos/uh88-weather" },
  { file: "IMG_7089-clip.webm", project: "uh88-weather", step: "process-4.0", caption: "", dir: "videos/uh88-weather" },
  { file: "IMG_7283-clip.webm", project: "uh88-weather", step: "gallery", caption: "", dir: "videos/uh88-weather" },
  { file: "IMG_7293-clip.webm", project: "uh88-weather", step: "gallery", caption: "", dir: "videos/uh88-weather" },
  { file: "IMG_2044-clip.webm", project: "stair-robot", step: "gallery", caption: "", dir: "videos/stair-robot" },
];
